[features]
seeds = false
skip-lint = false
[programs.devnet]
auction_house_v2 = "AHV2WqTNWDjBqY2zv9eUAMHneicckWf5NZxnPJvYxrkA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/athar/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
