[features]
seeds = false
skip-lint = false
[programs.Localnet]
auction_house_v2 = "AHV2XGm1jVAZp3NtwdVyHkbskbxk3oMfn73SXBkejUQb"
[programs.devnet]
auction_house_v2 = "AHV2XGm1jVAZp3NtwdVyHkbskbxk3oMfn73SXBkejUQb"

[workspace]
types = "../sdk/idl"
members = [
  "programs",
]

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "<WALLET_PATH>"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 js-tests/*.test.ts"
